import Head from 'next/head'
//import Image from 'next/image'
import { Inter } from '@next/font/google'
//import styles from '@/styles/Home.module.css'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillGithub, AiFillLinkedin} from 'react-icons/ai';
import Image from 'next/image';
import circlePortrait from '../public/portrait-circle.jpg';

import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';

import project1 from '../public/project1.png';
import project2 from '../public/project2.png';
import project3 from '../public/project3.png';

import {useState} from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Mitchell Foote's Professional Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Developer Portfolio:</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl"/>
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Mitchell Foote</h2>
            <h3 className="text-2xl py-2 md:text-3xl">Fullstack Software Developer</h3>
            <p className="text-md py-5 leading-6 text-gray-800 md:text-xl max-w-xl mx-auto">
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
              Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
              Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
              Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-12 py-4 text-gray-800">
            <AiFillGithub />
            <AiFillLinkedin />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-600 rounded-full w-80 h-80 overflow-hidden md:h-96 md:w-96">
            <Image src={circlePortrait} layout="fill" objectFit="cover"/>
          </div>
        </section>
        
        <section>
          <div className="text-center">
            <h3 className="text-2xl py-2">Skills and Knowledges:</h3>
            <p className="text-md py-5 leading-6 text-gray-800">
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
              Ut enim ad minim veniam, quis nostrud <span className="text-teal-600">exercitation</span> ullamco laboris nisi ut aliquip ex ea commodo consequat. 
              Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
              Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
            </p>
            <h3 className="text-2xl py-2">Languages:</h3>
            <ul className="text-md py-5 leading-6 text-gray-800">
              <li>Javascript</li>
              <li>C/C++</li>
              <li>HTML</li>
              <li>CSS</li>
            </ul>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={design} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
              <p className="py-2"> 
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
                Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-fray-800 py-1">photoshop</p>
              <p className="text-fray-800 py-1">photoshop</p>
              <p className="text-fray-800 py-1">photoshop</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={code} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
              <p className="py-2"> 
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
                Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-fray-800 py-1">photoshop</p>
              <p className="text-fray-800 py-1">photoshop</p>
              <p className="text-fray-800 py-1">photoshop</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={consulting} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
              <p className="py-2"> 
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
                Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-fray-800 py-1">photoshop</p>
              <p className="text-fray-800 py-1">photoshop</p>
              <p className="text-fray-800 py-1">photoshop</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-2">Portfolio</h3>
            <p className="text-md py-5 leading-6 text-gray-800">
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
              Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
              Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
              Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
            </p>
          </div>
          <div className="felx flex-co gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image src={project1} className="rounded-lg object-cover" width={'50%'} height="50%" layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={project2} className="rounded-lg object-cover" width={'50%'} height="50%" layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={project3} className="rounded-lg object-cover" width={'50%'} height="50%" layout="responsive"/>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
