import Head from 'next/head'
//import Image from 'next/image'
import { Inter } from '@next/font/google'
//import styles from '@/styles/Home.module.css'
import {BsFillMoonStarsFill} from 'react-icons/bs';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mitchell Foote's Professional Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="min-h-screen">
          <nav className="py-10">
            <h1>Mitchell Foote</h1>
            <ul>
              <li><BsFillMoonStarsFill/></li>
              <li><a>Resume</a></li>
            </ul>
          </nav>
        </section>
      </main>
    </div>
  )
}
